#!/bin/bash

# Update Debian APT Repository Script using reprepro
# This script uses reprepro to manage the repository instead of manual generation

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "Updating APT repository with reprepro..."

# Check if reprepro is installed
if ! command -v reprepro &> /dev/null; then
    echo "Error: reprepro is not installed. Please install it first:"
    echo "  sudo apt-get install reprepro"
    exit 1
fi

# Change to repository root
cd "$REPO_ROOT"

# Initialize repository if needed
if [ ! -d "dists" ]; then
    echo "Initializing repository..."
    reprepro -b . export stable
fi

# Check if there are any .deb files to add
if ls incoming/*.deb 1> /dev/null 2>&1; then
    echo "Adding packages to repository..."
    for deb in incoming/*.deb; do
        echo "Adding: $(basename "$deb")"
        reprepro -b . includedeb stable "$deb"
    done
    
    # Move processed packages to archive
    mkdir -p archive
    mv incoming/*.deb archive/
else
    echo "No .deb packages found in incoming/ directory"
fi

# Update repository metadata
echo "Updating repository metadata..."
reprepro -b . export stable

echo "Repository updated successfully!"
echo ""
echo "Repository structure:"
echo "  - dists/stable/Release (generated by reprepro)"
echo "  - dists/stable/main/binary-amd64/Packages (generated by reprepro)"
echo "  - pool/ (managed by reprepro)"
echo ""
echo "To add packages:"
echo "  1. Place .deb files in incoming/ directory"
echo "  2. Run this script again"
echo ""
echo "To deploy: wrangler deploy"